#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDATOS.DataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UDIE")]
	public partial class DbLibraryEntityDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAlumnosxRecursosAprendizaje(AlumnosxRecursosAprendizaje instance);
    partial void UpdateAlumnosxRecursosAprendizaje(AlumnosxRecursosAprendizaje instance);
    partial void DeleteAlumnosxRecursosAprendizaje(AlumnosxRecursosAprendizaje instance);
    partial void InsertAlumnos(Alumnos instance);
    partial void UpdateAlumnos(Alumnos instance);
    partial void DeleteAlumnos(Alumnos instance);
    partial void InsertCalendarioAcademico(CalendarioAcademico instance);
    partial void UpdateCalendarioAcademico(CalendarioAcademico instance);
    partial void DeleteCalendarioAcademico(CalendarioAcademico instance);
    partial void InsertCalendarioAcademicoxExamen(CalendarioAcademicoxExamen instance);
    partial void UpdateCalendarioAcademicoxExamen(CalendarioAcademicoxExamen instance);
    partial void DeleteCalendarioAcademicoxExamen(CalendarioAcademicoxExamen instance);
    partial void InsertCalendarioAcademicoxRecursosAprendizaje(CalendarioAcademicoxRecursosAprendizaje instance);
    partial void UpdateCalendarioAcademicoxRecursosAprendizaje(CalendarioAcademicoxRecursosAprendizaje instance);
    partial void DeleteCalendarioAcademicoxRecursosAprendizaje(CalendarioAcademicoxRecursosAprendizaje instance);
    partial void InsertComunicación(Comunicación instance);
    partial void UpdateComunicación(Comunicación instance);
    partial void DeleteComunicación(Comunicación instance);
    partial void InsertCursos(Cursos instance);
    partial void UpdateCursos(Cursos instance);
    partial void DeleteCursos(Cursos instance);
    partial void InsertExamenes(Examenes instance);
    partial void UpdateExamenes(Examenes instance);
    partial void DeleteExamenes(Examenes instance);
    partial void InsertProfesorxCurso(ProfesorxCurso instance);
    partial void UpdateProfesorxCurso(ProfesorxCurso instance);
    partial void DeleteProfesorxCurso(ProfesorxCurso instance);
    partial void InsertRecursosAprendizaje(RecursosAprendizaje instance);
    partial void UpdateRecursosAprendizaje(RecursosAprendizaje instance);
    partial void DeleteRecursosAprendizaje(RecursosAprendizaje instance);
    partial void InsertTareas(Tareas instance);
    partial void UpdateTareas(Tareas instance);
    partial void DeleteTareas(Tareas instance);
    partial void InsertProfesores(Profesores instance);
    partial void UpdateProfesores(Profesores instance);
    partial void DeleteProfesores(Profesores instance);
    #endregion
		
		public DbLibraryEntityDataContext() : 
				base(global::capaDATOS.Properties.Settings.Default.UDIEConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbLibraryEntityDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AlumnosxRecursosAprendizaje> AlumnosxRecursosAprendizaje
		{
			get
			{
				return this.GetTable<AlumnosxRecursosAprendizaje>();
			}
		}
		
		public System.Data.Linq.Table<Alumnos> Alumnos
		{
			get
			{
				return this.GetTable<Alumnos>();
			}
		}
		
		public System.Data.Linq.Table<CalendarioAcademico> CalendarioAcademico
		{
			get
			{
				return this.GetTable<CalendarioAcademico>();
			}
		}
		
		public System.Data.Linq.Table<CalendarioAcademicoxExamen> CalendarioAcademicoxExamen
		{
			get
			{
				return this.GetTable<CalendarioAcademicoxExamen>();
			}
		}
		
		public System.Data.Linq.Table<CalendarioAcademicoxRecursosAprendizaje> CalendarioAcademicoxRecursosAprendizaje
		{
			get
			{
				return this.GetTable<CalendarioAcademicoxRecursosAprendizaje>();
			}
		}
		
		public System.Data.Linq.Table<Comunicación> Comunicación
		{
			get
			{
				return this.GetTable<Comunicación>();
			}
		}
		
		public System.Data.Linq.Table<Cursos> Cursos
		{
			get
			{
				return this.GetTable<Cursos>();
			}
		}
		
		public System.Data.Linq.Table<Examenes> Examenes
		{
			get
			{
				return this.GetTable<Examenes>();
			}
		}
		
		public System.Data.Linq.Table<ProfesorxCurso> ProfesorxCurso
		{
			get
			{
				return this.GetTable<ProfesorxCurso>();
			}
		}
		
		public System.Data.Linq.Table<RecursosAprendizaje> RecursosAprendizaje
		{
			get
			{
				return this.GetTable<RecursosAprendizaje>();
			}
		}
		
		public System.Data.Linq.Table<Tareas> Tareas
		{
			get
			{
				return this.GetTable<Tareas>();
			}
		}
		
		public System.Data.Linq.Table<Profesores> Profesores
		{
			get
			{
				return this.GetTable<Profesores>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlumnosxRecursosAprendizaje")]
	public partial class AlumnosxRecursosAprendizaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AlumnoxRecursosAprendizajeID;
		
		private System.Nullable<int> _AlumnoID;
		
		private System.Nullable<int> _RecursosAprendizajeID;
		
		private string _Acceso;
		
		private string _Comentario;
		
		private string _Descripción;
		
		private EntityRef<Alumnos> _Alumnos;
		
		private EntityRef<RecursosAprendizaje> _RecursosAprendizaje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAlumnoxRecursosAprendizajeIDChanging(int value);
    partial void OnAlumnoxRecursosAprendizajeIDChanged();
    partial void OnAlumnoIDChanging(System.Nullable<int> value);
    partial void OnAlumnoIDChanged();
    partial void OnRecursosAprendizajeIDChanging(System.Nullable<int> value);
    partial void OnRecursosAprendizajeIDChanged();
    partial void OnAccesoChanging(string value);
    partial void OnAccesoChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public AlumnosxRecursosAprendizaje()
		{
			this._Alumnos = default(EntityRef<Alumnos>);
			this._RecursosAprendizaje = default(EntityRef<RecursosAprendizaje>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoxRecursosAprendizajeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AlumnoxRecursosAprendizajeID
		{
			get
			{
				return this._AlumnoxRecursosAprendizajeID;
			}
			set
			{
				if ((this._AlumnoxRecursosAprendizajeID != value))
				{
					this.OnAlumnoxRecursosAprendizajeIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoxRecursosAprendizajeID = value;
					this.SendPropertyChanged("AlumnoxRecursosAprendizajeID");
					this.OnAlumnoxRecursosAprendizajeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", DbType="Int")]
		public System.Nullable<int> AlumnoID
		{
			get
			{
				return this._AlumnoID;
			}
			set
			{
				if ((this._AlumnoID != value))
				{
					if (this._Alumnos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAlumnoIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoID = value;
					this.SendPropertyChanged("AlumnoID");
					this.OnAlumnoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecursosAprendizajeID", DbType="Int")]
		public System.Nullable<int> RecursosAprendizajeID
		{
			get
			{
				return this._RecursosAprendizajeID;
			}
			set
			{
				if ((this._RecursosAprendizajeID != value))
				{
					if (this._RecursosAprendizaje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRecursosAprendizajeIDChanging(value);
					this.SendPropertyChanging();
					this._RecursosAprendizajeID = value;
					this.SendPropertyChanged("RecursosAprendizajeID");
					this.OnRecursosAprendizajeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acceso", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Acceso
		{
			get
			{
				return this._Acceso;
			}
			set
			{
				if ((this._Acceso != value))
				{
					this.OnAccesoChanging(value);
					this.SendPropertyChanging();
					this._Acceso = value;
					this.SendPropertyChanged("Acceso");
					this.OnAccesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_AlumnosxRecursosAprendizaje", Storage="_Alumnos", ThisKey="AlumnoID", OtherKey="AlumnoID", IsForeignKey=true)]
		public Alumnos Alumnos
		{
			get
			{
				return this._Alumnos.Entity;
			}
			set
			{
				Alumnos previousValue = this._Alumnos.Entity;
				if (((previousValue != value) 
							|| (this._Alumnos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumnos.Entity = null;
						previousValue.AlumnosxRecursosAprendizaje.Remove(this);
					}
					this._Alumnos.Entity = value;
					if ((value != null))
					{
						value.AlumnosxRecursosAprendizaje.Add(this);
						this._AlumnoID = value.AlumnoID;
					}
					else
					{
						this._AlumnoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Alumnos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RecursosAprendizaje_AlumnosxRecursosAprendizaje", Storage="_RecursosAprendizaje", ThisKey="RecursosAprendizajeID", OtherKey="RecursosAprendizajeID", IsForeignKey=true)]
		public RecursosAprendizaje RecursosAprendizaje
		{
			get
			{
				return this._RecursosAprendizaje.Entity;
			}
			set
			{
				RecursosAprendizaje previousValue = this._RecursosAprendizaje.Entity;
				if (((previousValue != value) 
							|| (this._RecursosAprendizaje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RecursosAprendizaje.Entity = null;
						previousValue.AlumnosxRecursosAprendizaje.Remove(this);
					}
					this._RecursosAprendizaje.Entity = value;
					if ((value != null))
					{
						value.AlumnosxRecursosAprendizaje.Add(this);
						this._RecursosAprendizajeID = value.RecursosAprendizajeID;
					}
					else
					{
						this._RecursosAprendizajeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("RecursosAprendizaje");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumnos")]
	public partial class Alumnos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AlumnoID;
		
		private string _Nombre;
		
		private string _Identificación;
		
		private EntitySet<AlumnosxRecursosAprendizaje> _AlumnosxRecursosAprendizaje;
		
		private EntitySet<Comunicación> _Comunicación;
		
		private EntitySet<Examenes> _Examenes;
		
		private EntitySet<Tareas> _Tareas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAlumnoIDChanging(int value);
    partial void OnAlumnoIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdentificaciónChanging(string value);
    partial void OnIdentificaciónChanged();
    #endregion
		
		public Alumnos()
		{
			this._AlumnosxRecursosAprendizaje = new EntitySet<AlumnosxRecursosAprendizaje>(new Action<AlumnosxRecursosAprendizaje>(this.attach_AlumnosxRecursosAprendizaje), new Action<AlumnosxRecursosAprendizaje>(this.detach_AlumnosxRecursosAprendizaje));
			this._Comunicación = new EntitySet<Comunicación>(new Action<Comunicación>(this.attach_Comunicación), new Action<Comunicación>(this.detach_Comunicación));
			this._Examenes = new EntitySet<Examenes>(new Action<Examenes>(this.attach_Examenes), new Action<Examenes>(this.detach_Examenes));
			this._Tareas = new EntitySet<Tareas>(new Action<Tareas>(this.attach_Tareas), new Action<Tareas>(this.detach_Tareas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AlumnoID
		{
			get
			{
				return this._AlumnoID;
			}
			set
			{
				if ((this._AlumnoID != value))
				{
					this.OnAlumnoIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoID = value;
					this.SendPropertyChanged("AlumnoID");
					this.OnAlumnoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificación", DbType="VarChar(20)")]
		public string Identificación
		{
			get
			{
				return this._Identificación;
			}
			set
			{
				if ((this._Identificación != value))
				{
					this.OnIdentificaciónChanging(value);
					this.SendPropertyChanging();
					this._Identificación = value;
					this.SendPropertyChanged("Identificación");
					this.OnIdentificaciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_AlumnosxRecursosAprendizaje", Storage="_AlumnosxRecursosAprendizaje", ThisKey="AlumnoID", OtherKey="AlumnoID")]
		public EntitySet<AlumnosxRecursosAprendizaje> AlumnosxRecursosAprendizaje
		{
			get
			{
				return this._AlumnosxRecursosAprendizaje;
			}
			set
			{
				this._AlumnosxRecursosAprendizaje.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_Comunicación", Storage="_Comunicación", ThisKey="AlumnoID", OtherKey="AlumnoID")]
		public EntitySet<Comunicación> Comunicación
		{
			get
			{
				return this._Comunicación;
			}
			set
			{
				this._Comunicación.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_Examenes", Storage="_Examenes", ThisKey="AlumnoID", OtherKey="AlumnoID")]
		public EntitySet<Examenes> Examenes
		{
			get
			{
				return this._Examenes;
			}
			set
			{
				this._Examenes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_Tareas", Storage="_Tareas", ThisKey="AlumnoID", OtherKey="AlumnoID")]
		public EntitySet<Tareas> Tareas
		{
			get
			{
				return this._Tareas;
			}
			set
			{
				this._Tareas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AlumnosxRecursosAprendizaje(AlumnosxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = this;
		}
		
		private void detach_AlumnosxRecursosAprendizaje(AlumnosxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = null;
		}
		
		private void attach_Comunicación(Comunicación entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = this;
		}
		
		private void detach_Comunicación(Comunicación entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = null;
		}
		
		private void attach_Examenes(Examenes entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = this;
		}
		
		private void detach_Examenes(Examenes entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = null;
		}
		
		private void attach_Tareas(Tareas entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = this;
		}
		
		private void detach_Tareas(Tareas entity)
		{
			this.SendPropertyChanging();
			entity.Alumnos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalendarioAcademico")]
	public partial class CalendarioAcademico : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CalendarioAcademicoID;
		
		private string _Tipo;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Descripción;
		
		private EntitySet<CalendarioAcademicoxExamen> _CalendarioAcademicoxExamen;
		
		private EntitySet<CalendarioAcademicoxRecursosAprendizaje> _CalendarioAcademicoxRecursosAprendizaje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCalendarioAcademicoIDChanging(int value);
    partial void OnCalendarioAcademicoIDChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public CalendarioAcademico()
		{
			this._CalendarioAcademicoxExamen = new EntitySet<CalendarioAcademicoxExamen>(new Action<CalendarioAcademicoxExamen>(this.attach_CalendarioAcademicoxExamen), new Action<CalendarioAcademicoxExamen>(this.detach_CalendarioAcademicoxExamen));
			this._CalendarioAcademicoxRecursosAprendizaje = new EntitySet<CalendarioAcademicoxRecursosAprendizaje>(new Action<CalendarioAcademicoxRecursosAprendizaje>(this.attach_CalendarioAcademicoxRecursosAprendizaje), new Action<CalendarioAcademicoxRecursosAprendizaje>(this.detach_CalendarioAcademicoxRecursosAprendizaje));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarioAcademicoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CalendarioAcademicoID
		{
			get
			{
				return this._CalendarioAcademicoID;
			}
			set
			{
				if ((this._CalendarioAcademicoID != value))
				{
					this.OnCalendarioAcademicoIDChanging(value);
					this.SendPropertyChanging();
					this._CalendarioAcademicoID = value;
					this.SendPropertyChanged("CalendarioAcademicoID");
					this.OnCalendarioAcademicoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CalendarioAcademico_CalendarioAcademicoxExamen", Storage="_CalendarioAcademicoxExamen", ThisKey="CalendarioAcademicoID", OtherKey="CalendarioAcademicoID")]
		public EntitySet<CalendarioAcademicoxExamen> CalendarioAcademicoxExamen
		{
			get
			{
				return this._CalendarioAcademicoxExamen;
			}
			set
			{
				this._CalendarioAcademicoxExamen.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CalendarioAcademico_CalendarioAcademicoxRecursosAprendizaje", Storage="_CalendarioAcademicoxRecursosAprendizaje", ThisKey="CalendarioAcademicoID", OtherKey="CalendarioAcademicoID")]
		public EntitySet<CalendarioAcademicoxRecursosAprendizaje> CalendarioAcademicoxRecursosAprendizaje
		{
			get
			{
				return this._CalendarioAcademicoxRecursosAprendizaje;
			}
			set
			{
				this._CalendarioAcademicoxRecursosAprendizaje.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CalendarioAcademicoxExamen(CalendarioAcademicoxExamen entity)
		{
			this.SendPropertyChanging();
			entity.CalendarioAcademico = this;
		}
		
		private void detach_CalendarioAcademicoxExamen(CalendarioAcademicoxExamen entity)
		{
			this.SendPropertyChanging();
			entity.CalendarioAcademico = null;
		}
		
		private void attach_CalendarioAcademicoxRecursosAprendizaje(CalendarioAcademicoxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.CalendarioAcademico = this;
		}
		
		private void detach_CalendarioAcademicoxRecursosAprendizaje(CalendarioAcademicoxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.CalendarioAcademico = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalendarioAcademicoxExamen")]
	public partial class CalendarioAcademicoxExamen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CalendarioAcademicoxExamenID;
		
		private System.Nullable<int> _CalendarioAcademicoID;
		
		private System.Nullable<int> _ExamenID;
		
		private System.Nullable<System.DateTime> _Fecha_Examen;
		
		private System.Nullable<System.TimeSpan> _Hora_Examen;
		
		private EntityRef<CalendarioAcademico> _CalendarioAcademico;
		
		private EntityRef<Examenes> _Examenes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCalendarioAcademicoxExamenIDChanging(int value);
    partial void OnCalendarioAcademicoxExamenIDChanged();
    partial void OnCalendarioAcademicoIDChanging(System.Nullable<int> value);
    partial void OnCalendarioAcademicoIDChanged();
    partial void OnExamenIDChanging(System.Nullable<int> value);
    partial void OnExamenIDChanged();
    partial void OnFecha_ExamenChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ExamenChanged();
    partial void OnHora_ExamenChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHora_ExamenChanged();
    #endregion
		
		public CalendarioAcademicoxExamen()
		{
			this._CalendarioAcademico = default(EntityRef<CalendarioAcademico>);
			this._Examenes = default(EntityRef<Examenes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarioAcademicoxExamenID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CalendarioAcademicoxExamenID
		{
			get
			{
				return this._CalendarioAcademicoxExamenID;
			}
			set
			{
				if ((this._CalendarioAcademicoxExamenID != value))
				{
					this.OnCalendarioAcademicoxExamenIDChanging(value);
					this.SendPropertyChanging();
					this._CalendarioAcademicoxExamenID = value;
					this.SendPropertyChanged("CalendarioAcademicoxExamenID");
					this.OnCalendarioAcademicoxExamenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarioAcademicoID", DbType="Int")]
		public System.Nullable<int> CalendarioAcademicoID
		{
			get
			{
				return this._CalendarioAcademicoID;
			}
			set
			{
				if ((this._CalendarioAcademicoID != value))
				{
					if (this._CalendarioAcademico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCalendarioAcademicoIDChanging(value);
					this.SendPropertyChanging();
					this._CalendarioAcademicoID = value;
					this.SendPropertyChanged("CalendarioAcademicoID");
					this.OnCalendarioAcademicoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamenID", DbType="Int")]
		public System.Nullable<int> ExamenID
		{
			get
			{
				return this._ExamenID;
			}
			set
			{
				if ((this._ExamenID != value))
				{
					if (this._Examenes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExamenIDChanging(value);
					this.SendPropertyChanging();
					this._ExamenID = value;
					this.SendPropertyChanged("ExamenID");
					this.OnExamenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Examen", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Examen
		{
			get
			{
				return this._Fecha_Examen;
			}
			set
			{
				if ((this._Fecha_Examen != value))
				{
					this.OnFecha_ExamenChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Examen = value;
					this.SendPropertyChanged("Fecha_Examen");
					this.OnFecha_ExamenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora_Examen", DbType="Time")]
		public System.Nullable<System.TimeSpan> Hora_Examen
		{
			get
			{
				return this._Hora_Examen;
			}
			set
			{
				if ((this._Hora_Examen != value))
				{
					this.OnHora_ExamenChanging(value);
					this.SendPropertyChanging();
					this._Hora_Examen = value;
					this.SendPropertyChanged("Hora_Examen");
					this.OnHora_ExamenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CalendarioAcademico_CalendarioAcademicoxExamen", Storage="_CalendarioAcademico", ThisKey="CalendarioAcademicoID", OtherKey="CalendarioAcademicoID", IsForeignKey=true)]
		public CalendarioAcademico CalendarioAcademico
		{
			get
			{
				return this._CalendarioAcademico.Entity;
			}
			set
			{
				CalendarioAcademico previousValue = this._CalendarioAcademico.Entity;
				if (((previousValue != value) 
							|| (this._CalendarioAcademico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CalendarioAcademico.Entity = null;
						previousValue.CalendarioAcademicoxExamen.Remove(this);
					}
					this._CalendarioAcademico.Entity = value;
					if ((value != null))
					{
						value.CalendarioAcademicoxExamen.Add(this);
						this._CalendarioAcademicoID = value.CalendarioAcademicoID;
					}
					else
					{
						this._CalendarioAcademicoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("CalendarioAcademico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Examenes_CalendarioAcademicoxExamen", Storage="_Examenes", ThisKey="ExamenID", OtherKey="ExamenID", IsForeignKey=true)]
		public Examenes Examenes
		{
			get
			{
				return this._Examenes.Entity;
			}
			set
			{
				Examenes previousValue = this._Examenes.Entity;
				if (((previousValue != value) 
							|| (this._Examenes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Examenes.Entity = null;
						previousValue.CalendarioAcademicoxExamen.Remove(this);
					}
					this._Examenes.Entity = value;
					if ((value != null))
					{
						value.CalendarioAcademicoxExamen.Add(this);
						this._ExamenID = value.ExamenID;
					}
					else
					{
						this._ExamenID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Examenes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalendarioAcademicoxRecursosAprendizaje")]
	public partial class CalendarioAcademicoxRecursosAprendizaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CalendarioAcademicoxRecursosAprendizajeID;
		
		private System.Nullable<int> _CalendarioAcademicoID;
		
		private System.Nullable<int> _RecursosAprendizajeID;
		
		private EntityRef<CalendarioAcademico> _CalendarioAcademico;
		
		private EntityRef<RecursosAprendizaje> _RecursosAprendizaje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCalendarioAcademicoxRecursosAprendizajeIDChanging(int value);
    partial void OnCalendarioAcademicoxRecursosAprendizajeIDChanged();
    partial void OnCalendarioAcademicoIDChanging(System.Nullable<int> value);
    partial void OnCalendarioAcademicoIDChanged();
    partial void OnRecursosAprendizajeIDChanging(System.Nullable<int> value);
    partial void OnRecursosAprendizajeIDChanged();
    #endregion
		
		public CalendarioAcademicoxRecursosAprendizaje()
		{
			this._CalendarioAcademico = default(EntityRef<CalendarioAcademico>);
			this._RecursosAprendizaje = default(EntityRef<RecursosAprendizaje>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarioAcademicoxRecursosAprendizajeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CalendarioAcademicoxRecursosAprendizajeID
		{
			get
			{
				return this._CalendarioAcademicoxRecursosAprendizajeID;
			}
			set
			{
				if ((this._CalendarioAcademicoxRecursosAprendizajeID != value))
				{
					this.OnCalendarioAcademicoxRecursosAprendizajeIDChanging(value);
					this.SendPropertyChanging();
					this._CalendarioAcademicoxRecursosAprendizajeID = value;
					this.SendPropertyChanged("CalendarioAcademicoxRecursosAprendizajeID");
					this.OnCalendarioAcademicoxRecursosAprendizajeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarioAcademicoID", DbType="Int")]
		public System.Nullable<int> CalendarioAcademicoID
		{
			get
			{
				return this._CalendarioAcademicoID;
			}
			set
			{
				if ((this._CalendarioAcademicoID != value))
				{
					if (this._CalendarioAcademico.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCalendarioAcademicoIDChanging(value);
					this.SendPropertyChanging();
					this._CalendarioAcademicoID = value;
					this.SendPropertyChanged("CalendarioAcademicoID");
					this.OnCalendarioAcademicoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecursosAprendizajeID", DbType="Int")]
		public System.Nullable<int> RecursosAprendizajeID
		{
			get
			{
				return this._RecursosAprendizajeID;
			}
			set
			{
				if ((this._RecursosAprendizajeID != value))
				{
					if (this._RecursosAprendizaje.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRecursosAprendizajeIDChanging(value);
					this.SendPropertyChanging();
					this._RecursosAprendizajeID = value;
					this.SendPropertyChanged("RecursosAprendizajeID");
					this.OnRecursosAprendizajeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CalendarioAcademico_CalendarioAcademicoxRecursosAprendizaje", Storage="_CalendarioAcademico", ThisKey="CalendarioAcademicoID", OtherKey="CalendarioAcademicoID", IsForeignKey=true)]
		public CalendarioAcademico CalendarioAcademico
		{
			get
			{
				return this._CalendarioAcademico.Entity;
			}
			set
			{
				CalendarioAcademico previousValue = this._CalendarioAcademico.Entity;
				if (((previousValue != value) 
							|| (this._CalendarioAcademico.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CalendarioAcademico.Entity = null;
						previousValue.CalendarioAcademicoxRecursosAprendizaje.Remove(this);
					}
					this._CalendarioAcademico.Entity = value;
					if ((value != null))
					{
						value.CalendarioAcademicoxRecursosAprendizaje.Add(this);
						this._CalendarioAcademicoID = value.CalendarioAcademicoID;
					}
					else
					{
						this._CalendarioAcademicoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("CalendarioAcademico");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RecursosAprendizaje_CalendarioAcademicoxRecursosAprendizaje", Storage="_RecursosAprendizaje", ThisKey="RecursosAprendizajeID", OtherKey="RecursosAprendizajeID", IsForeignKey=true)]
		public RecursosAprendizaje RecursosAprendizaje
		{
			get
			{
				return this._RecursosAprendizaje.Entity;
			}
			set
			{
				RecursosAprendizaje previousValue = this._RecursosAprendizaje.Entity;
				if (((previousValue != value) 
							|| (this._RecursosAprendizaje.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._RecursosAprendizaje.Entity = null;
						previousValue.CalendarioAcademicoxRecursosAprendizaje.Remove(this);
					}
					this._RecursosAprendizaje.Entity = value;
					if ((value != null))
					{
						value.CalendarioAcademicoxRecursosAprendizaje.Add(this);
						this._RecursosAprendizajeID = value.RecursosAprendizajeID;
					}
					else
					{
						this._RecursosAprendizajeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("RecursosAprendizaje");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comunicación")]
	public partial class Comunicación : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ComunicaciónID;
		
		private System.Nullable<int> _AlumnoID;
		
		private System.Nullable<int> _CursoID;
		
		private string _Contenido;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Descripción;
		
		private EntityRef<Alumnos> _Alumnos;
		
		private EntityRef<Cursos> _Cursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnComunicaciónIDChanging(int value);
    partial void OnComunicaciónIDChanged();
    partial void OnAlumnoIDChanging(System.Nullable<int> value);
    partial void OnAlumnoIDChanged();
    partial void OnCursoIDChanging(System.Nullable<int> value);
    partial void OnCursoIDChanged();
    partial void OnContenidoChanging(string value);
    partial void OnContenidoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public Comunicación()
		{
			this._Alumnos = default(EntityRef<Alumnos>);
			this._Cursos = default(EntityRef<Cursos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComunicaciónID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ComunicaciónID
		{
			get
			{
				return this._ComunicaciónID;
			}
			set
			{
				if ((this._ComunicaciónID != value))
				{
					this.OnComunicaciónIDChanging(value);
					this.SendPropertyChanging();
					this._ComunicaciónID = value;
					this.SendPropertyChanged("ComunicaciónID");
					this.OnComunicaciónIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", DbType="Int")]
		public System.Nullable<int> AlumnoID
		{
			get
			{
				return this._AlumnoID;
			}
			set
			{
				if ((this._AlumnoID != value))
				{
					if (this._Alumnos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAlumnoIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoID = value;
					this.SendPropertyChanged("AlumnoID");
					this.OnAlumnoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoID", DbType="Int")]
		public System.Nullable<int> CursoID
		{
			get
			{
				return this._CursoID;
			}
			set
			{
				if ((this._CursoID != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCursoIDChanging(value);
					this.SendPropertyChanging();
					this._CursoID = value;
					this.SendPropertyChanged("CursoID");
					this.OnCursoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contenido", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Contenido
		{
			get
			{
				return this._Contenido;
			}
			set
			{
				if ((this._Contenido != value))
				{
					this.OnContenidoChanging(value);
					this.SendPropertyChanging();
					this._Contenido = value;
					this.SendPropertyChanged("Contenido");
					this.OnContenidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_Comunicación", Storage="_Alumnos", ThisKey="AlumnoID", OtherKey="AlumnoID", IsForeignKey=true)]
		public Alumnos Alumnos
		{
			get
			{
				return this._Alumnos.Entity;
			}
			set
			{
				Alumnos previousValue = this._Alumnos.Entity;
				if (((previousValue != value) 
							|| (this._Alumnos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumnos.Entity = null;
						previousValue.Comunicación.Remove(this);
					}
					this._Alumnos.Entity = value;
					if ((value != null))
					{
						value.Comunicación.Add(this);
						this._AlumnoID = value.AlumnoID;
					}
					else
					{
						this._AlumnoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Alumnos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Comunicación", Storage="_Cursos", ThisKey="CursoID", OtherKey="CursoID", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.Comunicación.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.Comunicación.Add(this);
						this._CursoID = value.CursoID;
					}
					else
					{
						this._CursoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cursos")]
	public partial class Cursos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CursoID;
		
		private string _Nombre;
		
		private string _Lugar;
		
		private string _Descripción;
		
		private EntitySet<Comunicación> _Comunicación;
		
		private EntitySet<Examenes> _Examenes;
		
		private EntitySet<ProfesorxCurso> _ProfesorxCurso;
		
		private EntitySet<Tareas> _Tareas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCursoIDChanging(int value);
    partial void OnCursoIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnLugarChanging(string value);
    partial void OnLugarChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public Cursos()
		{
			this._Comunicación = new EntitySet<Comunicación>(new Action<Comunicación>(this.attach_Comunicación), new Action<Comunicación>(this.detach_Comunicación));
			this._Examenes = new EntitySet<Examenes>(new Action<Examenes>(this.attach_Examenes), new Action<Examenes>(this.detach_Examenes));
			this._ProfesorxCurso = new EntitySet<ProfesorxCurso>(new Action<ProfesorxCurso>(this.attach_ProfesorxCurso), new Action<ProfesorxCurso>(this.detach_ProfesorxCurso));
			this._Tareas = new EntitySet<Tareas>(new Action<Tareas>(this.attach_Tareas), new Action<Tareas>(this.detach_Tareas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CursoID
		{
			get
			{
				return this._CursoID;
			}
			set
			{
				if ((this._CursoID != value))
				{
					this.OnCursoIDChanging(value);
					this.SendPropertyChanging();
					this._CursoID = value;
					this.SendPropertyChanged("CursoID");
					this.OnCursoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lugar", DbType="VarChar(255)")]
		public string Lugar
		{
			get
			{
				return this._Lugar;
			}
			set
			{
				if ((this._Lugar != value))
				{
					this.OnLugarChanging(value);
					this.SendPropertyChanging();
					this._Lugar = value;
					this.SendPropertyChanged("Lugar");
					this.OnLugarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Comunicación", Storage="_Comunicación", ThisKey="CursoID", OtherKey="CursoID")]
		public EntitySet<Comunicación> Comunicación
		{
			get
			{
				return this._Comunicación;
			}
			set
			{
				this._Comunicación.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Examenes", Storage="_Examenes", ThisKey="CursoID", OtherKey="CursoID")]
		public EntitySet<Examenes> Examenes
		{
			get
			{
				return this._Examenes;
			}
			set
			{
				this._Examenes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_ProfesorxCurso", Storage="_ProfesorxCurso", ThisKey="CursoID", OtherKey="CursoID")]
		public EntitySet<ProfesorxCurso> ProfesorxCurso
		{
			get
			{
				return this._ProfesorxCurso;
			}
			set
			{
				this._ProfesorxCurso.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Tareas", Storage="_Tareas", ThisKey="CursoID", OtherKey="CursoID")]
		public EntitySet<Tareas> Tareas
		{
			get
			{
				return this._Tareas;
			}
			set
			{
				this._Tareas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comunicación(Comunicación entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_Comunicación(Comunicación entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
		
		private void attach_Examenes(Examenes entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_Examenes(Examenes entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
		
		private void attach_ProfesorxCurso(ProfesorxCurso entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_ProfesorxCurso(ProfesorxCurso entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
		
		private void attach_Tareas(Tareas entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = this;
		}
		
		private void detach_Tareas(Tareas entity)
		{
			this.SendPropertyChanging();
			entity.Cursos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Examenes")]
	public partial class Examenes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExamenID;
		
		private System.Nullable<int> _AlumnoID;
		
		private System.Nullable<int> _CursoID;
		
		private System.Nullable<System.DateTime> _Fecha_Examen;
		
		private System.Nullable<int> _Valor;
		
		private string _Descripción;
		
		private EntitySet<CalendarioAcademicoxExamen> _CalendarioAcademicoxExamen;
		
		private EntityRef<Alumnos> _Alumnos;
		
		private EntityRef<Cursos> _Cursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExamenIDChanging(int value);
    partial void OnExamenIDChanged();
    partial void OnAlumnoIDChanging(System.Nullable<int> value);
    partial void OnAlumnoIDChanged();
    partial void OnCursoIDChanging(System.Nullable<int> value);
    partial void OnCursoIDChanged();
    partial void OnFecha_ExamenChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_ExamenChanged();
    partial void OnValorChanging(System.Nullable<int> value);
    partial void OnValorChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public Examenes()
		{
			this._CalendarioAcademicoxExamen = new EntitySet<CalendarioAcademicoxExamen>(new Action<CalendarioAcademicoxExamen>(this.attach_CalendarioAcademicoxExamen), new Action<CalendarioAcademicoxExamen>(this.detach_CalendarioAcademicoxExamen));
			this._Alumnos = default(EntityRef<Alumnos>);
			this._Cursos = default(EntityRef<Cursos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExamenID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ExamenID
		{
			get
			{
				return this._ExamenID;
			}
			set
			{
				if ((this._ExamenID != value))
				{
					this.OnExamenIDChanging(value);
					this.SendPropertyChanging();
					this._ExamenID = value;
					this.SendPropertyChanged("ExamenID");
					this.OnExamenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", DbType="Int")]
		public System.Nullable<int> AlumnoID
		{
			get
			{
				return this._AlumnoID;
			}
			set
			{
				if ((this._AlumnoID != value))
				{
					if (this._Alumnos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAlumnoIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoID = value;
					this.SendPropertyChanged("AlumnoID");
					this.OnAlumnoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoID", DbType="Int")]
		public System.Nullable<int> CursoID
		{
			get
			{
				return this._CursoID;
			}
			set
			{
				if ((this._CursoID != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCursoIDChanging(value);
					this.SendPropertyChanging();
					this._CursoID = value;
					this.SendPropertyChanged("CursoID");
					this.OnCursoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Examen", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Examen
		{
			get
			{
				return this._Fecha_Examen;
			}
			set
			{
				if ((this._Fecha_Examen != value))
				{
					this.OnFecha_ExamenChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Examen = value;
					this.SendPropertyChanged("Fecha_Examen");
					this.OnFecha_ExamenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Int")]
		public System.Nullable<int> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Examenes_CalendarioAcademicoxExamen", Storage="_CalendarioAcademicoxExamen", ThisKey="ExamenID", OtherKey="ExamenID")]
		public EntitySet<CalendarioAcademicoxExamen> CalendarioAcademicoxExamen
		{
			get
			{
				return this._CalendarioAcademicoxExamen;
			}
			set
			{
				this._CalendarioAcademicoxExamen.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_Examenes", Storage="_Alumnos", ThisKey="AlumnoID", OtherKey="AlumnoID", IsForeignKey=true)]
		public Alumnos Alumnos
		{
			get
			{
				return this._Alumnos.Entity;
			}
			set
			{
				Alumnos previousValue = this._Alumnos.Entity;
				if (((previousValue != value) 
							|| (this._Alumnos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumnos.Entity = null;
						previousValue.Examenes.Remove(this);
					}
					this._Alumnos.Entity = value;
					if ((value != null))
					{
						value.Examenes.Add(this);
						this._AlumnoID = value.AlumnoID;
					}
					else
					{
						this._AlumnoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Alumnos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Examenes", Storage="_Cursos", ThisKey="CursoID", OtherKey="CursoID", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.Examenes.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.Examenes.Add(this);
						this._CursoID = value.CursoID;
					}
					else
					{
						this._CursoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CalendarioAcademicoxExamen(CalendarioAcademicoxExamen entity)
		{
			this.SendPropertyChanging();
			entity.Examenes = this;
		}
		
		private void detach_CalendarioAcademicoxExamen(CalendarioAcademicoxExamen entity)
		{
			this.SendPropertyChanging();
			entity.Examenes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProfesorxCurso")]
	public partial class ProfesorxCurso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProfesorxCursoID;
		
		private System.Nullable<int> _ProfesorID;
		
		private System.Nullable<int> _CursoID;
		
		private string _Descripción;
		
		private EntityRef<Cursos> _Cursos;
		
		private EntityRef<Profesores> _Profesores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProfesorxCursoIDChanging(int value);
    partial void OnProfesorxCursoIDChanged();
    partial void OnProfesorIDChanging(System.Nullable<int> value);
    partial void OnProfesorIDChanged();
    partial void OnCursoIDChanging(System.Nullable<int> value);
    partial void OnCursoIDChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public ProfesorxCurso()
		{
			this._Cursos = default(EntityRef<Cursos>);
			this._Profesores = default(EntityRef<Profesores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfesorxCursoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProfesorxCursoID
		{
			get
			{
				return this._ProfesorxCursoID;
			}
			set
			{
				if ((this._ProfesorxCursoID != value))
				{
					this.OnProfesorxCursoIDChanging(value);
					this.SendPropertyChanging();
					this._ProfesorxCursoID = value;
					this.SendPropertyChanged("ProfesorxCursoID");
					this.OnProfesorxCursoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfesorID", DbType="Int")]
		public System.Nullable<int> ProfesorID
		{
			get
			{
				return this._ProfesorID;
			}
			set
			{
				if ((this._ProfesorID != value))
				{
					if (this._Profesores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProfesorIDChanging(value);
					this.SendPropertyChanging();
					this._ProfesorID = value;
					this.SendPropertyChanged("ProfesorID");
					this.OnProfesorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoID", DbType="Int")]
		public System.Nullable<int> CursoID
		{
			get
			{
				return this._CursoID;
			}
			set
			{
				if ((this._CursoID != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCursoIDChanging(value);
					this.SendPropertyChanging();
					this._CursoID = value;
					this.SendPropertyChanged("CursoID");
					this.OnCursoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_ProfesorxCurso", Storage="_Cursos", ThisKey="CursoID", OtherKey="CursoID", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.ProfesorxCurso.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.ProfesorxCurso.Add(this);
						this._CursoID = value.CursoID;
					}
					else
					{
						this._CursoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesore_ProfesorxCurso", Storage="_Profesores", ThisKey="ProfesorID", OtherKey="ProfesorID", IsForeignKey=true)]
		public Profesores Profesores
		{
			get
			{
				return this._Profesores.Entity;
			}
			set
			{
				Profesores previousValue = this._Profesores.Entity;
				if (((previousValue != value) 
							|| (this._Profesores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesores.Entity = null;
						previousValue.ProfesorxCursos.Remove(this);
					}
					this._Profesores.Entity = value;
					if ((value != null))
					{
						value.ProfesorxCursos.Add(this);
						this._ProfesorID = value.ProfesorID;
					}
					else
					{
						this._ProfesorID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Profesores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecursosAprendizaje")]
	public partial class RecursosAprendizaje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecursosAprendizajeID;
		
		private string _Tipo;
		
		private string _Formato;
		
		private string _Descripción;
		
		private EntitySet<AlumnosxRecursosAprendizaje> _AlumnosxRecursosAprendizaje;
		
		private EntitySet<CalendarioAcademicoxRecursosAprendizaje> _CalendarioAcademicoxRecursosAprendizaje;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecursosAprendizajeIDChanging(int value);
    partial void OnRecursosAprendizajeIDChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnFormatoChanging(string value);
    partial void OnFormatoChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public RecursosAprendizaje()
		{
			this._AlumnosxRecursosAprendizaje = new EntitySet<AlumnosxRecursosAprendizaje>(new Action<AlumnosxRecursosAprendizaje>(this.attach_AlumnosxRecursosAprendizaje), new Action<AlumnosxRecursosAprendizaje>(this.detach_AlumnosxRecursosAprendizaje));
			this._CalendarioAcademicoxRecursosAprendizaje = new EntitySet<CalendarioAcademicoxRecursosAprendizaje>(new Action<CalendarioAcademicoxRecursosAprendizaje>(this.attach_CalendarioAcademicoxRecursosAprendizaje), new Action<CalendarioAcademicoxRecursosAprendizaje>(this.detach_CalendarioAcademicoxRecursosAprendizaje));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecursosAprendizajeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RecursosAprendizajeID
		{
			get
			{
				return this._RecursosAprendizajeID;
			}
			set
			{
				if ((this._RecursosAprendizajeID != value))
				{
					this.OnRecursosAprendizajeIDChanging(value);
					this.SendPropertyChanging();
					this._RecursosAprendizajeID = value;
					this.SendPropertyChanged("RecursosAprendizajeID");
					this.OnRecursosAprendizajeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(50)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Formato", DbType="VarChar(50)")]
		public string Formato
		{
			get
			{
				return this._Formato;
			}
			set
			{
				if ((this._Formato != value))
				{
					this.OnFormatoChanging(value);
					this.SendPropertyChanging();
					this._Formato = value;
					this.SendPropertyChanged("Formato");
					this.OnFormatoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RecursosAprendizaje_AlumnosxRecursosAprendizaje", Storage="_AlumnosxRecursosAprendizaje", ThisKey="RecursosAprendizajeID", OtherKey="RecursosAprendizajeID")]
		public EntitySet<AlumnosxRecursosAprendizaje> AlumnosxRecursosAprendizaje
		{
			get
			{
				return this._AlumnosxRecursosAprendizaje;
			}
			set
			{
				this._AlumnosxRecursosAprendizaje.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="RecursosAprendizaje_CalendarioAcademicoxRecursosAprendizaje", Storage="_CalendarioAcademicoxRecursosAprendizaje", ThisKey="RecursosAprendizajeID", OtherKey="RecursosAprendizajeID")]
		public EntitySet<CalendarioAcademicoxRecursosAprendizaje> CalendarioAcademicoxRecursosAprendizaje
		{
			get
			{
				return this._CalendarioAcademicoxRecursosAprendizaje;
			}
			set
			{
				this._CalendarioAcademicoxRecursosAprendizaje.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AlumnosxRecursosAprendizaje(AlumnosxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.RecursosAprendizaje = this;
		}
		
		private void detach_AlumnosxRecursosAprendizaje(AlumnosxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.RecursosAprendizaje = null;
		}
		
		private void attach_CalendarioAcademicoxRecursosAprendizaje(CalendarioAcademicoxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.RecursosAprendizaje = this;
		}
		
		private void detach_CalendarioAcademicoxRecursosAprendizaje(CalendarioAcademicoxRecursosAprendizaje entity)
		{
			this.SendPropertyChanging();
			entity.RecursosAprendizaje = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tareas")]
	public partial class Tareas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TareaID;
		
		private System.Nullable<int> _AlumnoID;
		
		private System.Nullable<int> _CursoID;
		
		private System.Nullable<System.DateTime> _Fecha_Entrega;
		
		private System.Nullable<int> _Valor;
		
		private string _Descripción;
		
		private EntityRef<Alumnos> _Alumnos;
		
		private EntityRef<Cursos> _Cursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTareaIDChanging(int value);
    partial void OnTareaIDChanged();
    partial void OnAlumnoIDChanging(System.Nullable<int> value);
    partial void OnAlumnoIDChanged();
    partial void OnCursoIDChanging(System.Nullable<int> value);
    partial void OnCursoIDChanged();
    partial void OnFecha_EntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_EntregaChanged();
    partial void OnValorChanging(System.Nullable<int> value);
    partial void OnValorChanged();
    partial void OnDescripciónChanging(string value);
    partial void OnDescripciónChanged();
    #endregion
		
		public Tareas()
		{
			this._Alumnos = default(EntityRef<Alumnos>);
			this._Cursos = default(EntityRef<Cursos>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TareaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TareaID
		{
			get
			{
				return this._TareaID;
			}
			set
			{
				if ((this._TareaID != value))
				{
					this.OnTareaIDChanging(value);
					this.SendPropertyChanging();
					this._TareaID = value;
					this.SendPropertyChanged("TareaID");
					this.OnTareaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlumnoID", DbType="Int")]
		public System.Nullable<int> AlumnoID
		{
			get
			{
				return this._AlumnoID;
			}
			set
			{
				if ((this._AlumnoID != value))
				{
					if (this._Alumnos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAlumnoIDChanging(value);
					this.SendPropertyChanging();
					this._AlumnoID = value;
					this.SendPropertyChanged("AlumnoID");
					this.OnAlumnoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CursoID", DbType="Int")]
		public System.Nullable<int> CursoID
		{
			get
			{
				return this._CursoID;
			}
			set
			{
				if ((this._CursoID != value))
				{
					if (this._Cursos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCursoIDChanging(value);
					this.SendPropertyChanging();
					this._CursoID = value;
					this.SendPropertyChanged("CursoID");
					this.OnCursoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Entrega", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Entrega
		{
			get
			{
				return this._Fecha_Entrega;
			}
			set
			{
				if ((this._Fecha_Entrega != value))
				{
					this.OnFecha_EntregaChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Entrega = value;
					this.SendPropertyChanged("Fecha_Entrega");
					this.OnFecha_EntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Int")]
		public System.Nullable<int> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this.OnDescripciónChanging(value);
					this.SendPropertyChanging();
					this._Descripción = value;
					this.SendPropertyChanged("Descripción");
					this.OnDescripciónChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumnos_Tareas", Storage="_Alumnos", ThisKey="AlumnoID", OtherKey="AlumnoID", IsForeignKey=true)]
		public Alumnos Alumnos
		{
			get
			{
				return this._Alumnos.Entity;
			}
			set
			{
				Alumnos previousValue = this._Alumnos.Entity;
				if (((previousValue != value) 
							|| (this._Alumnos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumnos.Entity = null;
						previousValue.Tareas.Remove(this);
					}
					this._Alumnos.Entity = value;
					if ((value != null))
					{
						value.Tareas.Add(this);
						this._AlumnoID = value.AlumnoID;
					}
					else
					{
						this._AlumnoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Alumnos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cursos_Tareas", Storage="_Cursos", ThisKey="CursoID", OtherKey="CursoID", IsForeignKey=true)]
		public Cursos Cursos
		{
			get
			{
				return this._Cursos.Entity;
			}
			set
			{
				Cursos previousValue = this._Cursos.Entity;
				if (((previousValue != value) 
							|| (this._Cursos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cursos.Entity = null;
						previousValue.Tareas.Remove(this);
					}
					this._Cursos.Entity = value;
					if ((value != null))
					{
						value.Tareas.Add(this);
						this._CursoID = value.CursoID;
					}
					else
					{
						this._CursoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cursos");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profesores")]
	public partial class Profesores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProfesorID;
		
		private string _Nombre;
		
		private string _Cédula;
		
		private EntitySet<ProfesorxCurso> _ProfesorxCursos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProfesorIDChanging(int value);
    partial void OnProfesorIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCédulaChanging(string value);
    partial void OnCédulaChanged();
    #endregion
		
		public Profesores()
		{
			this._ProfesorxCursos = new EntitySet<ProfesorxCurso>(new Action<ProfesorxCurso>(this.attach_ProfesorxCursos), new Action<ProfesorxCurso>(this.detach_ProfesorxCursos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfesorID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProfesorID
		{
			get
			{
				return this._ProfesorID;
			}
			set
			{
				if ((this._ProfesorID != value))
				{
					this.OnProfesorIDChanging(value);
					this.SendPropertyChanging();
					this._ProfesorID = value;
					this.SendPropertyChanged("ProfesorID");
					this.OnProfesorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cédula", DbType="VarChar(20)")]
		public string Cédula
		{
			get
			{
				return this._Cédula;
			}
			set
			{
				if ((this._Cédula != value))
				{
					this.OnCédulaChanging(value);
					this.SendPropertyChanging();
					this._Cédula = value;
					this.SendPropertyChanged("Cédula");
					this.OnCédulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesore_ProfesorxCurso", Storage="_ProfesorxCursos", ThisKey="ProfesorID", OtherKey="ProfesorID")]
		public EntitySet<ProfesorxCurso> ProfesorxCursos
		{
			get
			{
				return this._ProfesorxCursos;
			}
			set
			{
				this._ProfesorxCursos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProfesorxCursos(ProfesorxCurso entity)
		{
			this.SendPropertyChanging();
			entity.Profesores = this;
		}
		
		private void detach_ProfesorxCursos(ProfesorxCurso entity)
		{
			this.SendPropertyChanging();
			entity.Profesores = null;
		}
	}
}
#pragma warning restore 1591
